services:
  postgres:
    container_name: postgres-container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123Gobruins!
    ports: 
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

