spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ufcdb
    username: postgres
    password: 123Gobruins!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true